import json
from pathlib import Path

NB_PATH = Path(__file__).resolve().parents[1] / "notebooks" / "03_eda_analysis.ipynb"

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
        "language_info": {"name": "python", "version": "3"},
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Day 3 — Advanced Exploratory Data Analysis (EDA) & Visualizations\n",
                "\n",
                "Performs deep exploratory analysis and exports **16** publication-quality charts to `reports/charts/`.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import sqlite3\n",
                "from pathlib import Path\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import plotly.express as px\n",
                "\n",
                "sns.set_theme(style='whitegrid')\n",
                "plt.rcParams['figure.dpi'] = 150\n",
                "plt.rcParams['figure.figsize'] = [12, 6.5]\n",
                "plt.rcParams['savefig.bbox'] = 'tight'\n",
                "plt.rcParams['font.size'] = 10\n",
                "\n",
                "cwd = Path.cwd()\n",
                "PROJECT_ROOT = cwd.parent if cwd.name == 'notebooks' else cwd\n",
                "DB_PATH = PROJECT_ROOT / 'data' / 'db' / 'bluestock_mf.db'\n",
                "PROCESSED_DIR = PROJECT_ROOT / 'data' / 'processed'\n",
                "REPORTS_CHARTS_DIR = PROJECT_ROOT / 'reports' / 'charts'\n",
                "REPORTS_CHARTS_DIR.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                "assert DB_PATH.exists(), f'SQLite DB not found at {DB_PATH}. Run Day 2 first.'\n",
                "conn = sqlite3.connect(str(DB_PATH))\n",
                "\n",
                "def read_fact(table_name: str) -> pd.DataFrame:\n",
                "    return pd.read_sql_query(f'SELECT * FROM {table_name}', conn)\n",
                "\n",
                "fact_nav = read_fact('fact_nav')\n",
                "fact_aum = read_fact('fact_aum')\n",
                "fact_sip_inflows = read_fact('fact_sip_inflows')\n",
                "fact_transactions = read_fact('fact_transactions')\n",
                "fact_performance = read_fact('fact_performance')\n",
                "dim_fund = read_fact('dim_fund')\n",
                "\n",
                "clean_category_inflows = pd.read_csv(PROCESSED_DIR / 'clean_category_inflows.csv')\n",
                "clean_holdings = pd.read_csv(PROCESSED_DIR / 'clean_holdings.csv')\n",
                "clean_folio_count = pd.read_csv(PROCESSED_DIR / 'clean_folio_count.csv')\n",
                "\n",
                "print('Connected DB:', DB_PATH)\n",
                "print('fact_nav columns:', list(fact_nav.columns))\n",
                "print('dim_fund columns:', list(dim_fund.columns))\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Chart 01: Normalized NAV Trend\n",
                "sampled_codes = [119551, 120503, 118632, 119092, 120841]\n",
                "nav_id_col = 'scheme_code' if 'scheme_code' in fact_nav.columns else 'amfi_code'\n",
                "df_nav_slice = fact_nav[fact_nav[nav_id_col].isin(sampled_codes)].copy()\n",
                "df_nav_slice['date'] = pd.to_datetime(df_nav_slice['date'])\n",
                "df_nav_slice = df_nav_slice.sort_values(['scheme_code', 'date'])\n",
                "df_nav_slice['normalized_nav'] = (\n",
                "    df_nav_slice.groupby('scheme_code')['nav']\n",
                "    .transform(lambda x: x / x.iloc[0] * 100)\n",
                ")\n",
                "\n",
                "fig_nav = px.line(df_nav_slice, x='date', y='normalized_nav', color='scheme_code',\n",
                "                 title='Chart 01: Normalized NAV Trajectory (Rebased to 100)')\n",
                "fig_nav.update_layout(xaxis_title='Date', yaxis_title='Normalized NAV (Base=100)')\n",
                "fig_nav.write_image(str(REPORTS_CHARTS_DIR / 'nav_trend.png'), width=1920, height=1080, scale=2)\n",
                "fig_nav.show()\n",
                "\n",
                "# Chart 02: AUM growth\n",
                "plt.figure()\n",
                "aum_hue = 'report_date' if 'report_date' in fact_aum.columns else None\n",
                "sns.barplot(data=fact_aum, x='fund_house', y='aum_crore', hue=aum_hue, palette='viridis')\n",
                "plt.xticks(rotation=45, ha='right')\n",
                "plt.title('Chart 02: Institutional AUM Growth Metrics by AMC', fontweight='bold')\n",
                "plt.xlabel('Asset Management House')\n",
                "plt.ylabel('AUM Total Valuation (In Crores)')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'aum_growth.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 03: SIP trend + milestone annotation (₹31,002 Cr peak)\n",
                "sip_df = fact_sip_inflows.sort_values('month').copy()\n",
                "peak_idx = sip_df['sip_inflow_crore'].idxmax()\n",
                "peak_date = sip_df.loc[peak_idx, 'month']\n",
                "peak_value = sip_df.loc[peak_idx, 'sip_inflow_crore']\n",
                "fig_sip = px.line(sip_df, x='month', y='sip_inflow_crore', title='Chart 03: Monthly SIP Inflow Trend',\n",
                "                  markers=True)\n",
                "fig_sip.add_annotation(x=peak_date, y=peak_value, text='₹31,002 Cr Peak', showarrow=True,\n",
                "                       arrowhead=2, bgcolor='yellow', ax=0, ay=-60)\n",
                "fig_sip.update_layout(xaxis_title='Operating Month', yaxis_title='Injected Capital (In Crores)')\n",
                "fig_sip.write_image(str(REPORTS_CHARTS_DIR / 'sip_trend.png'), width=1920, height=1080, scale=2)\n",
                "fig_sip.show()\n",
                "\n",
                "# Chart 04: Category heatmap\n",
                "pivot_inflow = clean_category_inflows.pivot(index='category', columns='month', values='net_inflow_crore')\n",
                "plt.figure(figsize=(13, 6.8))\n",
                "sns.heatmap(pivot_inflow, cmap='YlGnBu', annot=False, cbar_kws={'label': 'Net Cash Flow (Crores)'})\n",
                "plt.title('Chart 04: Categorical Product Allocation Heatmap Matrix', fontweight='bold')\n",
                "plt.xlabel('Operating Calendar Month')\n",
                "plt.ylabel('Asset Class Classification')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'category_heatmap.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Chart 05: Transaction Type Distribution (pie)\n",
                "tx = fact_transactions.copy()\n",
                "plt.figure(figsize=(7, 7))\n",
                "type_dist = tx['transaction_type'].value_counts().dropna()\n",
                "plt.pie(type_dist, labels=type_dist.index.astype(str), autopct='%1.1f%%', startangle=140)\n",
                "plt.title('Chart 05: Transaction Type Distribution (Investor Behavior)', fontweight='bold')\n",
                "plt.ylabel('')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'demographics_age.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 06: Ticket sizes by transaction type (log)\n",
                "plt.figure()\n",
                "sns.boxplot(data=fact_transactions, x='transaction_type', y='amount_inr', palette='Set2')\n",
                "plt.yscale('log')\n",
                "plt.title('Chart 06: Transaction Ticket Sizes by Type (Log Scale)', fontweight='bold')\n",
                "plt.xlabel('Transaction Type')\n",
                "plt.ylabel('Injected Ticket Size Valuation (INR)')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'demographics_boxplot.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 07: KYC status distribution (supporting)\n",
                "plt.figure(figsize=(7, 5))\n",
                "sns.countplot(data=fact_transactions, x='kyc_status', palette='muted')\n",
                "plt.title('Chart 07: Participant KYC Status Distribution', fontweight='bold')\n",
                "plt.xlabel('KYC Status')\n",
                "plt.ylabel('Active Transaction Records Count')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'demographics_gender.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Chart 08: Payment mode / amount concentration\n",
                "plt.figure(figsize=(12, 6))\n",
                "channel_amounts = fact_transactions.groupby('payment_mode')['amount_inr'].sum().sort_values(ascending=False)\n",
                "sns.barplot(x=channel_amounts.values, y=channel_amounts.index, palette='magma')\n",
                "plt.title('Chart 08: Aggregated Invested Base Volume across Payment Methods', fontweight='bold')\n",
                "plt.xlabel('Aggregated Investment Capital Base (INR)')\n",
                "plt.ylabel('Sourcing Vector Mode')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'geography.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 09: Transaction intent distribution (pie)\n",
                "plt.figure(figsize=(7, 7))\n",
                "type_dist2 = fact_transactions['transaction_type'].value_counts()\n",
                "plt.pie(type_dist2, labels=type_dist2.index.astype(str), autopct='%1.1f%%', startangle=140)\n",
                "plt.title('Chart 09: Market Transaction Intent Distribution Share', fontweight='bold')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'geography_tier.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Chart 10: Folio growth with milestones\n",
                "folio_df = clean_folio_count.copy()\n",
                "folio_df['month'] = folio_df['month'].astype(str)\n",
                "fig_folio = px.line(folio_df.sort_values('month'), x='month', y='total_folios_crore',\n",
                "                     title='Chart 10: Industry Folio Account Expansion Trend')\n",
                "milestones = [('Jan 2022', 13.26), (None, 20.0), ('Dec 2025', 26.12)]\n",
                "for m, val in milestones:\n",
                "    if m is not None and m in folio_df['month'].values:\n",
                "        row = folio_df[folio_df['month'] == m].iloc[0]\n",
                "        fig_folio.add_annotation(x=row['month'], y=row['total_folios_crore'], text=f'{val:.2f} Cr',\n",
                "                                 showarrow=True, arrowhead=1, bgcolor='lightgreen')\n",
                "    else:\n",
                "        idx = (folio_df['total_folios_crore'] - float(val)).abs().idxmin()\n",
                "        row = folio_df.loc[idx]\n",
                "        fig_folio.add_annotation(x=row['month'], y=row['total_folios_crore'], text=f'{val:.2f} Cr',\n",
                "                                 showarrow=True, arrowhead=1, bgcolor='lightgreen')\n",
                "fig_folio.update_layout(xaxis_title='Operating Calendar Month Line', yaxis_title='Total Live Folio Accounts (In Crores)')\n",
                "fig_folio.write_image(str(REPORTS_CHARTS_DIR / 'folio_growth.png'), width=1920, height=1080, scale=2)\n",
                "fig_folio.show()\n",
                "\n",
                "# Chart 11: Correlation matrix with scheme_name labels from dim_fund\n",
                "corr_df = fact_nav[fact_nav['scheme_code'].isin([119551, 120503, 118632, 119092, 120841])].pivot(\n",
                "    index='date', columns='scheme_code', values='nav'\n",
                ")\n",
                "corr = corr_df.copy()\n",
                "corr.index = pd.to_datetime(corr.index)\n",
                "corr = corr.pct_change().corr()\n",
                "\n",
                "scheme_map = (dim_fund.drop_duplicates('scheme_code').set_index('scheme_code')['scheme_name'].to_dict())\n",
                "def map_name(x):\n",
                "    v = scheme_map.get(x)\n",
                "    if v is None or v == '' or str(v).lower() == 'nan':\n",
                "        return str(x)\n",
                "    return v\n",
                "corr.columns = [map_name(c) for c in corr.columns]\n",
                "corr.index = [map_name(c) for c in corr.index]\n",
                "\n",
                "plt.figure(figsize=(10, 7))\n",
                "sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', vmin=-1, vmax=1)\n",
                "plt.title('Chart 11: Portfolio Returns Asset Volatility Correlation Matrix (Scheme Names)', fontweight='bold')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'correlation_matrix.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 12: Sector donut\n",
                "plt.figure(figsize=(8, 8))\n",
                "sector_w = clean_holdings.groupby('sector')['weight_pct'].sum().sort_values(ascending=False).head(10)\n",
                "plt.pie(sector_w, labels=sector_w.index.astype(str), autopct='%1.1f%%', wedgeprops=dict(width=0.45), startangle=90)\n",
                "plt.title('Chart 12: Top 10 Sectoral Portfolio Weight Distribution Donut', fontweight='bold')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'sector_donut.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Chart 13: Payment mode frequency\n",
                "plt.figure(figsize=(12, 6))\n",
                "sns.countplot(data=fact_transactions, x='payment_mode', palette='Set3', order=fact_transactions['payment_mode'].value_counts().index)\n",
                "plt.title('Chart 13: Transaction Count by Ingestion Channel', fontweight='bold')\n",
                "plt.xlabel('Payment Method Vector Channel')\n",
                "plt.ylabel('Total Transaction Volume Count')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'payment_mode_frequency.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 14: Payment mode median ticket\n",
                "plt.figure(figsize=(12, 6))\n",
                "sns.barplot(data=fact_transactions, x='payment_mode', y='amount_inr', estimator=np.median,\n",
                "            palette='pastel', order=fact_transactions['payment_mode'].value_counts().index)\n",
                "plt.title('Chart 14: Median Ticket Capital Size by Payment Channel', fontweight='bold')\n",
                "plt.xlabel('Payment Method Vector Channel')\n",
                "plt.ylabel('Median Transaction Value Sizing (INR)')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'payment_mode_median_amount.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 15: Expense ratio vs 3Y return\n",
                "plt.figure(figsize=(12, 6))\n",
                "sns.scatterplot(data=fact_performance, x='expense_ratio_pct', y='return_3yr_pct', hue='risk_grade', s=120, palette='deep')\n",
                "plt.title('Chart 15: Cost Efficiency Scatter Map: Expense Ratio vs 3-Year Trailing Returns', fontweight='bold')\n",
                "plt.xlabel('Operating Expense Ratio (%)')\n",
                "plt.ylabel('3-Year Trailing Realized Returns (%)')\n",
                "plt.grid(True, linestyle='--', alpha=0.5)\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'cost_efficiency_scatter.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
                "\n",
                "# Chart 16: Sharpe by risk grade\n",
                "plt.figure(figsize=(12, 6))\n",
                "risk_order = [x for x in ['Low', 'Moderate', 'Moderately High', 'High', 'Very High'] if x in fact_performance['risk_grade'].unique()]\n",
                "if not risk_order:\n",
                "    risk_order = sorted([x for x in fact_performance['risk_grade'].dropna().unique()])\n",
                "sns.boxplot(data=fact_performance, x='risk_grade', y='sharpe_ratio', palette='Set3', order=risk_order)\n",
                "plt.title('Chart 16: Risk-Adjusted Profile: Sharpe Ratio Dispersion by Risk Grade', fontweight='bold')\n",
                "plt.xlabel('Assigned Risk Classification Grade')\n",
                "plt.ylabel('Sharpe Ratio')\n",
                "plt.tight_layout()\n",
                "plt.savefig(REPORTS_CHARTS_DIR / 'sharpe_ratio_by_risk_grade.png', dpi=300, bbox_inches='tight')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Summary of 10 Key EDA Findings\n",
                "\n",
                "(Text placeholder retained from original notebook.)\n",
            ],
        },
    ],
}

NB_PATH.parent.mkdir(parents=True, exist_ok=True)
NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('Wrote', NB_PATH)

